version: '3'
services:
  web:
    container_name: nginx-server
    image: changwei1997/nginx:latest
    ports:
      - "80:80"
    volumes:
      - "/root/docker/nginx/www:/usr/share/nginx/html"
      - "/root/docker/nginx/conf:/etc/nginx"
      - "/root/docker/nginx/logs:/var/log/nginx"
    expose:
      - "80"
# volumes:
#   nginx: {}
