version: '3'
services:
  web:
    container_name: nginx-server
    image: changwei1997/nginx:latest
    ports:
      - "80:80"
    volumes:
      - "/root/docker/nginx/logs:/var/log/nginx"
    expose:
      - "80"
    external_links:
      - "changwei-homepage"
      # - "changwei-homepage-dev"
# volumes:
#   nginx: {}
