# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install-deps:
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync

  build-docker:
    steps:
      # - run:
      #     name: docker install
      #     command: |          
      #       sudo apt-get remove docker docker-engine docker.io containerd runc
      #       sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
      #       echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #       curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      #       sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
      #     no_output_timeout: 15m
      - run:
          name: docker login
          command: docker login --username changwei1997 --password ${DOCKER_HUB_PASSWORD}
          no_output_timeout: 15m
      - run:
          name: docker build
          command: docker build . -t changwei1997/nginx:latest
          no_output_timeout: 15m
      - run:
          name: docker push
          command: docker push changwei1997/nginx:latest
          no_output_timeout: 15m

  deploy:
    steps:
      - run:
          name: Deploy to HOST_QCLOUD_SH_1_HOST
          command: |
            ssh-keyscan "${HOST_QCLOUD_SH_1_IP}" >> ~/.ssh/known_hosts 2>/dev/null
            ssh ${SERVER_USER}@${SERVER_HOST} 'sudo mkdir -m 775 -p /root/docker/nginx /root/docker/nginx/logs'
            rsync -av --delete ./docker-compose.yml ${SERVER_USER}@${SERVER_HOST}:/root/docker/nginx/
            ssh ${SERVER_USER}@${SERVER_HOST} 'cd /root/docker/nginx && docker-compose down --rmi all && docker-compose up -d --force-recreate'

jobs:
  deploy:
    docker:
      - image: circleci/node:14.13.0
        # auth:
        #   username: changwei1997
        #   password: ${DOCKER_HUB_PASSWORD}
    steps:
      - install-deps
      - build-docker
      - deploy

workflows:
  workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
